# Generated by Django 5.1.2 on 2024-10-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symtoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
