# Generated by Django 5.1.2 on 2024-10-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_doctor_review_appointment_symtoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symtoms',
            new_name='symptoms',
        ),
    ]
