<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-11 15:17
=======
# Generated by Django 4.2.1 on 2024-10-11 15:30
>>>>>>> 6613e9e0ef903fa4bdd8992acf0dc0f8cf5e8016

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
