# Generated by Django 5.1.2 on 2024-10-10 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('endocrinologist', 'Endocrinologist'), ('gastroenterologist', 'Gastroenterologist'), ('nephrologist', 'Nephrologist'), ('neurologist', 'Neurologist'), ('oncologist', 'Oncologist'), ('ophthalmologist', 'Ophthalmologist'), ('orthopedic', 'Orthopedic'), ('otolaryngologist', 'Otolaryngologist'), ('pediatrician', 'Pediatrician'), ('pulmonologist', 'Pulmonologist'), ('psychiatrist', 'Psychiatrist'), ('rheumatologist', 'Rheumatologist'), ('urologist', 'Urologist'), ('dentist', 'Dentist'), ('general_physician', 'General Physician'), ('surgeon', 'Surgeon')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('consultation_fee', models.IntegerField()),
                ('designation', models.CharField(choices=[('senior_consultant', 'Senior Consultant'), ('junior_consultant', 'Junior Consultant'), ('medicine_special', 'Medicine Specialist'), ('medical_officer', 'Medical Officer'), ('surgeon', 'Surgeon'), ('pediatrician', 'Pediatrician')], max_length=20)),
                ('image', models.ImageField(upload_to='doctor_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ManyToManyField(to='doctor.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.ManyToManyField(to='doctor.dayofweek')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='doctor.doctor')),
            ],
        ),
    ]
