# Generated by Django 4.2.1 on 2024-10-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('consultation_fee', models.IntegerField()),
                ('designation', models.CharField(choices=[('senior_consultant', 'Senior Consultant'), ('junior_consultant', 'Junior Consultant'), ('medicine_special', 'Medicine Specialist'), ('medical_officer', 'Medical Officer'), ('surgeon', 'Surgeon'), ('pediatrician', 'Pediatrician')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor/')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('gastroenterologist', 'Gastroenterologist'), ('neurologist', 'Neurologist'), ('general_physician', 'General Physician')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.ManyToManyField(to='doctor.dayofweek')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='patient.patientprofile')),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialist',
            field=models.ManyToManyField(to='doctor.specialist'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
