# Generated by Django 5.1.2 on 2024-10-10 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('consultation_fee', models.IntegerField()),
                ('designation', models.CharField(choices=[('senior_consultant', 'Senior Consultant'), ('junior_consultant', 'Junior Consultant'), ('medicine_special', 'Medicine Specialist'), ('medical_officer', 'Medical Officer'), ('surgeon', 'Surgeon'), ('pediatrician', 'Pediatrician')], max_length=20)),
                ('image', models.ImageField(upload_to='doctor/')),
                ('specialist', models.ManyToManyField(to='doctor.specialist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='doctorworktime',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='doctor.doctorprofile'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
