# Generated by Django 5.1.2 on 2024-10-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='designation',
            field=models.CharField(choices=[('senior_consultant', 'Senior Consultant'), ('junior_consultant', 'Junior Consultant'), ('medicine_specialist', 'Medicine Specialist'), ('medical_officer', 'Medical Officer'), ('surgeon', 'Surgeon'), ('pediatrician', 'Pediatrician')], max_length=20),
        ),
    ]
