# Generated by Django 4.2.1 on 2024-10-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('gastroenterologist', 'Gastroenterologist'), ('neurologist', 'Neurologist'), ('general_physician', 'General Physician'), ('surgeon', 'Surgeon')], max_length=50),
        ),
    ]
