# Generated by Django 5.1.2 on 2024-10-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('gastroenterologist', 'Gastroenterologist'), ('neurologist', 'Neurologist'), ('general_physician', 'General Physician'), ('surgeon', 'Surgeon')], max_length=50),
        ),
        migrations.CreateModel(
            name='DoctorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctor.doctorprofile')),
            ],
        ),
    ]
