# Generated by Django 5.1.2 on 2024-10-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_specialist_name_doctorrating'),
        ('patient', '0002_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrating',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='patient.patientprofile'),
            preserve_default=False,
        ),
    ]
